"""
Pipeline context diagram — what to run and in what order.
Outputs: context_diagram.pdf / .png
"""

import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch

matplotlib.rcParams["font.family"] = "DejaVu Sans"

BG       = "#0D1117"
C_EXT    = "#3B3B5C"   # external input (data / binary on disk)
C_LIB    = "#1C4E6B"   # library module (.py, never run directly)
C_RUN    = "#2A6647"   # step to run (notebook / script)
C_DATA   = "#5C4B1A"   # data file produced
C_FIG    = "#5C2A2A"   # output figure / paper product
C_OLD    = "#333333"   # superseded / reference-only
TXT      = "white"
ARROW    = "#888899"

FIG_W, FIG_H = 11, 9.5

fig, ax = plt.subplots(figsize=(FIG_W, FIG_H))
ax.set_xlim(0, 1); ax.set_ylim(0, 1)
ax.axis("off")
fig.patch.set_facecolor(BG)
ax.set_facecolor(BG)


# ── helpers ───────────────────────────────────────────────────────────────────
def box(ax, x, y, text, color, w=0.18, h=0.062, fs=7.4, bold=False):
    p = FancyBboxPatch((x - w/2, y - h/2), w, h,
                       boxstyle="round,pad=0.025", linewidth=0,
                       facecolor=color, transform=ax.transAxes,
                       clip_on=False, zorder=3)
    ax.add_patch(p)
    ax.text(x, y, text, color=TXT, fontsize=fs,
            weight="bold" if bold else "normal",
            ha="center", va="center", linespacing=1.4,
            transform=ax.transAxes, zorder=4)

def arr(ax, x0, y0, x1, y1, col=ARROW, style="-|>"):
    ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                xycoords="axes fraction",
                arrowprops=dict(arrowstyle=style, color=col, lw=1.2),
                zorder=5)

def label(ax, x, y, text, col="#AAAACC", fs=6.8, bold=False):
    ax.text(x, y, text, color=col, fontsize=fs,
            weight="bold" if bold else "normal",
            ha="center", va="center", transform=ax.transAxes,
            clip_on=False)


# ── TITLE ─────────────────────────────────────────────────────────────────────
ax.text(0.5, 0.975, "VDP Pipeline — Context & Run Order",
        color="white", fontsize=11, weight="bold",
        ha="center", va="top", transform=ax.transAxes)

# ── ROW 0: External inputs ────────────────────────────────────────────────────
label(ax, 0.5, 0.925, "EXTERNAL INPUTS  (must exist on disk, not generated by this project)", bold=True)

box(ax, 0.17, 0.870, "S3M catalogue\n(FITS/CSV files\non disk)", C_EXT, w=0.17)
box(ax, 0.50, 0.870, "input_neomod3.dat\n(NEOMOD3 orbital\ndistribution bins)", C_EXT, w=0.17)
box(ax, 0.83, 0.870, "digest2 binary\n(external MPC tool\nat D2_DIR)", C_EXT, w=0.17)

# ── ROW 1: Library modules ────────────────────────────────────────────────────
label(ax, 0.5, 0.800, "LIBRARY MODULES  (import only, never run directly)", bold=True)

box(ax, 0.20, 0.755, "s3m_loader.py\nloads S3M orbital\nelements → DataFrame", C_LIB, w=0.19)
box(ax, 0.50, 0.755, "neoscore.py\nKepler propagation\n+ observer geometry", C_LIB, w=0.19)
box(ax, 0.80, 0.755, "velocity_density_\npipeline.py\nmain pipeline module", C_LIB, w=0.19, bold=True)

# faint dependency arrows from S3M → s3m_loader, neomod3 → neoscore, etc.
arr(ax, 0.17, 0.839, 0.20, 0.786, col="#555566")
arr(ax, 0.50, 0.839, 0.50, 0.786, col="#555566")
arr(ax, 0.83, 0.839, 0.80, 0.786, col="#555566")
# s3m_loader → vdp
arr(ax, 0.295, 0.755, 0.695, 0.755, col="#555566")
# neoscore → vdp
arr(ax, 0.595, 0.755, 0.695, 0.755, col="#555566")

# ── divider ───────────────────────────────────────────────────────────────────
ax.axhline(0.710, xmin=0.03, xmax=0.97, color="#333355", lw=0.9, zorder=1)

# ── STEP 1 ────────────────────────────────────────────────────────────────────
label(ax, 0.5, 0.686, "STEP 1 — Build probability maps  (run once, ~1 hour)", bold=True)

box(ax, 0.25, 0.640, "download_prob_maps\n.ipynb\ncalls vdp.generate_\nprobability_maps()", C_RUN, w=0.22, h=0.075, bold=True)
box(ax, 0.72, 0.640, "prob_maps_\n2025-03-21.npz\n4 pops × 8 mag bins\nvelocity-density maps", C_DATA, w=0.22, h=0.075)

arr(ax, 0.80, 0.724, 0.25+0.001, 0.724, col="#555566")   # vdp.py → notebook (import)
arr(ax, 0.360, 0.640, 0.610, 0.640)                       # notebook → npz

# ── STEP 2 ────────────────────────────────────────────────────────────────────
label(ax, 0.5, 0.553, "STEP 2 — Score S3M + run digest2  (run once, ~1 hour)", bold=True)

box(ax, 0.25, 0.505, "run_digest2_\ncomparison.py\npropagates S3M,\nscores VDP + digest2", C_RUN, w=0.22, h=0.075, bold=True)

# inputs to step 2
arr(ax, 0.72, 0.617, 0.72, 0.550, col=ARROW)              # npz down then right
arr(ax, 0.72, 0.550, 0.361, 0.520, col=ARROW)             # → script

arr(ax, 0.83, 0.724, 0.83, 0.560, col="#555566")          # digest2 binary
arr(ax, 0.83, 0.560, 0.361, 0.510, col="#555566")

# outputs of step 2
box(ax, 0.68, 0.540, "s3m_digest2_comparison\n_vdp_input.parquet\n(checkpoint after VDP\nscoring, before digest2)", C_DATA, w=0.24, h=0.068, fs=7.0)
box(ax, 0.68, 0.455, "s3m_digest2_\ncomparison.parquet\nboth P_NEO_vdp and\nP_NEO_d2 columns", C_DATA, w=0.24, h=0.068)

arr(ax, 0.361, 0.530, 0.560, 0.543)                       # → vdp_input parquet
arr(ax, 0.361, 0.495, 0.560, 0.458)                       # → final parquet

# ── divider ───────────────────────────────────────────────────────────────────
ax.axhline(0.405, xmin=0.03, xmax=0.97, color="#333355", lw=0.9, zorder=1)

# ── STEP 3 ────────────────────────────────────────────────────────────────────
label(ax, 0.5, 0.383, "STEP 3 — Analysis & figures  (notebooks, run after step 2)", bold=True)

# 3a: digest2_comparison.ipynb
box(ax, 0.22, 0.318, "digest2_comparison\n.ipynb\nreads final parquet,\nROC + score plots", C_RUN, w=0.22, h=0.075)
box(ax, 0.22, 0.218, "poster / paper\nfigures 3–5\n(ROC, score dists,\nobservable plots)", C_FIG, w=0.22, h=0.068)
arr(ax, 0.68, 0.421, 0.68, 0.380, col=ARROW)
arr(ax, 0.68, 0.380, 0.331, 0.332, col=ARROW)             # parquet → notebook
arr(ax, 0.22, 0.280, 0.22, 0.252)                          # notebook → figures

# 3b: paper_figures_ecliptic_strip.ipynb
box(ax, 0.60, 0.318, "paper_figures_\necliptic_strip.ipynb\nreads npz,\necliptic strip + prob maps", C_RUN, w=0.24, h=0.075)
box(ax, 0.60, 0.218, "paper figures 1–2\n(ecliptic strip,\npopulation\nvelocity maps)", C_FIG, w=0.22, h=0.068)
arr(ax, 0.72, 0.617, 0.72, 0.380, col=ARROW)
arr(ax, 0.72, 0.380, 0.720, 0.356, col=ARROW)             # npz → notebook
arr(ax, 0.60, 0.280, 0.60, 0.252)

# ── SUPERSEDED (bottom-right note) ───────────────────────────────────────────
box(ax, 0.83, 0.280, "s3m_scored_\n2025-03-21.parquet\n(pre-digest2, Apr 29)\nread by ROCcurve.ipynb", C_OLD, w=0.22, h=0.075, fs=6.8)
ax.text(0.83, 0.208, "⚠  superseded by\ns3m_digest2_comparison\n.parquet", color="#888888",
        fontsize=6.5, ha="center", va="top", transform=ax.transAxes, linespacing=1.4)

# ── LEGEND ────────────────────────────────────────────────────────────────────
patches = [
    mpatches.Patch(color=C_EXT,  label="External input (must exist)"),
    mpatches.Patch(color=C_LIB,  label="Library module (import only)"),
    mpatches.Patch(color=C_RUN,  label="Run this (notebook / script)"),
    mpatches.Patch(color=C_DATA, label="Data file produced"),
    mpatches.Patch(color=C_FIG,  label="Output figure / paper product"),
    mpatches.Patch(color=C_OLD,  label="Superseded / reference only"),
]
ax.legend(handles=patches, loc="lower center", ncol=6,
          fontsize=6.3, framealpha=0.0, labelcolor="white",
          bbox_to_anchor=(0.5, 0.005),
          handlelength=1.2, handletextpad=0.4, columnspacing=0.8)

plt.tight_layout(pad=0.3)
fig.savefig("context_diagram.pdf", bbox_inches="tight", dpi=200,
            facecolor=fig.get_facecolor())
fig.savefig("context_diagram.png", bbox_inches="tight", dpi=200,
            facecolor=fig.get_facecolor())
print("Saved context_diagram.pdf and .png")
plt.show()
